name: Metrics (optional)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  metrics:
    if: ${{ secrets.METRICS_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Arudchayan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          output_action: commit
          committer_message: "chore: refresh metrics"
          filename: assets/metrics.svg
